apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  rules:
  - host: "weather.vpakhai-ocg1.link"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-service
            port:
              number: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mon-ingress
  namespace: monitoring
spec:
  rules:
  - host: "prometheus.vpakhai-ocg1.link"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090


 - host: "grafana.vpakhai-ocg1.link"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80

  - host: "alertmanager.vpakhai-ocg1.link"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-kube-prometheus-alertmanager
            port:
              number: 9093
